name: Build movies.json

on:
  push:
    branches: [main]
    paths:
      - 'data/**'
      - 'scripts/**'
      - 'package.json'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
      - name: Commit movies.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'build: update movies.json'
          file_pattern: movies.json
